# Todo 3
Christopher Lagunilla  
Due Tuesday, September 12

## Installing and Using Pandas
- requires NumPy to be installed
- "pd" is the conventional abbreviation

In [1]:
# importing pandas
import pandas as pd
import numpy

# check version
pd.__version__

'0.20.3'

## Pandas Objects
### Series: a one-dimensional array of indexed data
    - can be created from a list or array
    - wraps both a sequence of values and a sequence of indices
        - values and indices are accessible
        - values are returned as a NumPy array

In [2]:
data = pd.Series([0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0])
data

0    0.0
1    0.5
2    1.0
3    1.5
4    2.0
5    2.5
6    3.0
dtype: float64

In [3]:
print(data.values)
print(data.index)

[ 0.   0.5  1.   1.5  2.   2.5  3. ]
RangeIndex(start=0, stop=7, step=1)

#### Series as Generalized NumPy Array
- Series is interchangable with a 1D NumPy array
    - difference is presence of the index attribute
    - implicit vs. explicit indices
- Series indices can be any type, not just integers

In [4]:
data = pd.Series([0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0], index=['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh'])
data

first      0.0
second     0.5
third      1.0
fourth     1.5
fifth      2.0
sixth      2.5
seventh    3.0
dtype: float64

#### Series as Specialized Dictionary
- Python Dictionary: maps arbitrary keys to arbitrary values
- Pandas Series: maps typed keys to typed values
- dictionaries can be used to create a Series

In [5]:
dict = {'one':1, 'two':2, 'three':3}
series = pd.Series(dict)
series

one      1
three    3
two      2
dtype: int64

- Series will be created with sorted keys become the indices

#### Constructing Series Objects
- Ways to Construct:
    1. use Series Constructor
    2. use list as parameter
    3. use dictionary as parameter

### The Pandas DataFrame Object
#### DataFrame As A Generalized NumPy Array
- 2D array with flexible row indices and flexible column names
- in a chart, indices are the row headers and values are column headers

In [6]:
pdict = {'one':1, 'two':2, 'three':3}
letters = {'one':'A', 'two':'B', 'three':'C'}
dict_series = pd.Series(pdict)
letters_series = pd.Series(letters)

new_series = pd.DataFrame({'col1':dict_series, 'col2':letters_series})
new_series

       col1 col2
one       1    A
three     3    C
two       2    B

#### DataFrame as Specialized Dictionary
- DataFrame maps a column name to a Series of column data

#### Constructing DataFrame Objects
1. From a single Series object
2. From a list of dictionaries
3. From a dictionary of Series objects
4. From a 2D NumPy array
5. From a NumPy structured array

### The Pandas Index Object
- an immutable array that allows a user to reference data

#### Index as Immutable Array
- the Index object can use standard Python indexing
- similar attributes to NumPy arrays
- Index object cannot use normal means to modify array elements

#### Index As Ordered Set
- follows the conventions of Python's Set data structure

## Data Indexing and Selection
- Data can be accessed using dictionary notation, 1D array notation

#### Indexers: loc, iloc, and ix
- loc: function to expose explicit index
- iloc: allows for indexing using normal Python convention
- ix: hybrid of loc and iloc

## Operating on Data in Pandas
### Ufuncs: Index Preservation
- NumPy ufuncs word on Padas Series and DataFrame objects
- applying a ufunc __preserves__ indices

### Ufuncs: Index Alignment
#### Index Alignment in Series
- non entries are marked with NaN to maintain alignment

#### Index Alignment in DataFrame
- in DataFrames, NaN is used in both cells regardless of the order of the two objects

### Ufuncs: Operations Between DataFrame and Series
- row-wise operations

In [7]:
import csv
zip_codes = pd.read_csv('zipcodes_chris.csv', names=['ZIP', 'City', 'County'])

zip_codes.values

array([['ZIP', 'City', 'County'],
       ['15001', 'Aliquippa', 'Beaver'],
       ['15003', 'Ambridge', 'Beaver'],
       ...,
       ['19611', 'Reading', 'Berks'],
       ['19612', 'Reading', 'Berks'],
       ['19640', 'Reading', 'Berks']], dtype=object)

In [8]:
zip_codes.T

,0,1,2,3,4,5,6,7,8,9,...,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205
ZIP,ZIP,15001,15003,15004,15005,15006,15007,15009,15010,15012,...,19604,19605,19606,19607,19608,19609,19610,19611,19612,19640
City,City,Aliquippa,Ambridge,Atlasburg,Baden,Bairdford,Bakerstown,Beaver,Beaver Falls,Belle Vernon,...,Reading,Reading,Reading,Reading,Reading,Reading,Reading,Reading,Reading,Reading
County,County,Beaver,Beaver,Washington,Beaver,Allegheny,Allegheny,Beaver,Beaver,Fayette,...,Berks,Berks,Berks,Berks,Berks,Berks,Berks,Berks,Berks,Berks

In [9]:
zip_codes.describe

<bound method NDFrame.describe of         ZIP              City      County
0       ZIP              City      County
1     15001         Aliquippa      Beaver
2     15003          Ambridge      Beaver
3     15004         Atlasburg  Washington
4     15005             Baden      Beaver
5     15006         Bairdford   Allegheny
6     15007        Bakerstown   Allegheny
7     15009            Beaver      Beaver
8     15010      Beaver Falls      Beaver
9     15012      Belle Vernon     Fayette
10    15014      Brackenridge   Allegheny
11    15015     Bradfordwoods   Allegheny
12    15017       Bridgeville   Allegheny
13    15018       Buena Vista   Allegheny
14    15019            Bulger  Washington
15    15020            Bunola   Allegheny
16    15021      Burgettstown  Washington
17    15022         Charleroi  Washington
18    15024          Cheswick   Allegheny
19    15025          Clairton   Allegheny
20    15026           Clinton      Beaver
21    15027            Conway      Beaver
22    15028          Coulters   Allegheny
23    15030         Creighton   Allegheny
24    15031             Cuddy   Allegheny
25    15032       Curtisville   Allegheny
26    15033            Donora  Washington
27    15034        Dravosburg   Allegheny
28    15035  East Mc Keesport   Allegheny
29    15037         Elizabeth   Allegheny
...     ...               ...         ...
2176  19542  Monocacy Station       Berks
2177  19543        Morgantown       Berks
2178  19544       Mount Aetna       Berks
2179  19545   New Berlinville       Berks
2180  19547              Oley       Berks
2181  19548        Pine Forge       Berks
2182  19549      Port Clinton  Schuylkill
2183  19550       Rehrersburg       Berks
2184  19551         Robesonia       Berks
2185  19554     Shartlesville       Berks
2186  19555   Shoemakersville       Berks
2187  19559       Strausstown       Berks
2188  19560            Temple       Berks
2189  19562            Topton       Berks
2190  19564       Virginville       Berks
2191  19565      Wernersville       Berks
2192  19567        Womelsdorf       Berks
2193  19601           Reading       Berks
2194  19602           Reading       Berks
2195  19603           Reading       Berks
2196  19604           Reading       Berks
2197  19605           Reading       Berks
2198  19606           Reading       Berks
2199  19607           Reading       Berks
2200  19608           Reading       Berks
2201  19609           Reading       Berks
2202  19610           Reading       Berks
2203  19611           Reading       Berks
2204  19612           Reading       Berks
2205  19640           Reading       Berks

[2206 rows x 3 columns]>

In [10]:
# concatenate two columns across the DataFrame
zip_codes['ZIP/City'] = zip_codes['ZIP'] + ": " + zip_codes['County']
zip_codes[:20]

      ZIP           City      County           ZIP/City
0     ZIP           City      County        ZIP: County
1   15001      Aliquippa      Beaver      15001: Beaver
2   15003       Ambridge      Beaver      15003: Beaver
3   15004      Atlasburg  Washington  15004: Washington
4   15005          Baden      Beaver      15005: Beaver
5   15006      Bairdford   Allegheny   15006: Allegheny
6   15007     Bakerstown   Allegheny   15007: Allegheny
7   15009         Beaver      Beaver      15009: Beaver
8   15010   Beaver Falls      Beaver      15010: Beaver
9   15012   Belle Vernon     Fayette     15012: Fayette
10  15014   Brackenridge   Allegheny   15014: Allegheny
11  15015  Bradfordwoods   Allegheny   15015: Allegheny
12  15017    Bridgeville   Allegheny   15017: Allegheny
13  15018    Buena Vista   Allegheny   15018: Allegheny
14  15019         Bulger  Washington  15019: Washington
15  15020         Bunola   Allegheny   15020: Allegheny
16  15021   Burgettstown  Washington  15021: Washington
17  15022      Charleroi  Washington  15022: Washington
18  15024       Cheswick   Allegheny   15024: Allegheny
19  15025       Clairton   Allegheny   15025: Allegheny

In [11]:
# reset Indexes to be the ZIP codes
zip_codes = zip_codes[1:].set_index('ZIP')
zip_codes

                   City      County           ZIP/City
ZIP
15001         Aliquippa      Beaver      15001: Beaver
15003          Ambridge      Beaver      15003: Beaver
15004         Atlasburg  Washington  15004: Washington
15005             Baden      Beaver      15005: Beaver
15006         Bairdford   Allegheny   15006: Allegheny
15007        Bakerstown   Allegheny   15007: Allegheny
15009            Beaver      Beaver      15009: Beaver
15010      Beaver Falls      Beaver      15010: Beaver
15012      Belle Vernon     Fayette     15012: Fayette
15014      Brackenridge   Allegheny   15014: Allegheny
15015     Bradfordwoods   Allegheny   15015: Allegheny
15017       Bridgeville   Allegheny   15017: Allegheny
15018       Buena Vista   Allegheny   15018: Allegheny
15019            Bulger  Washington  15019: Washington
15020            Bunola   Allegheny   15020: Allegheny
15021      Burgettstown  Washington  15021: Washington
15022         Charleroi  Washington  15022: Washington
15024          Cheswick   Allegheny   15024: Allegheny
15025          Clairton   Allegheny   15025: Allegheny
15026           Clinton      Beaver      15026: Beaver
15027            Conway      Beaver      15027: Beaver
15028          Coulters   Allegheny   15028: Allegheny
15030         Creighton   Allegheny   15030: Allegheny
15031             Cuddy   Allegheny   15031: Allegheny
15032       Curtisville   Allegheny   15032: Allegheny
15033            Donora  Washington  15033: Washington
15034        Dravosburg   Allegheny   15034: Allegheny
15035  East Mc Keesport   Allegheny   15035: Allegheny
15037         Elizabeth   Allegheny   15037: Allegheny
15038            Elrama  Washington  15038: Washington
...                 ...         ...                ...
19542  Monocacy Station       Berks       19542: Berks
19543        Morgantown       Berks       19543: Berks
19544       Mount Aetna       Berks       19544: Berks
19545   New Berlinville       Berks       19545: Berks
19547              Oley       Berks       19547: Berks
19548        Pine Forge       Berks       19548: Berks
19549      Port Clinton  Schuylkill  19549: Schuylkill
19550       Rehrersburg       Berks       19550: Berks
19551         Robesonia       Berks       19551: Berks
19554     Shartlesville       Berks       19554: Berks
19555   Shoemakersville       Berks       19555: Berks
19559       Strausstown       Berks       19559: Berks
19560            Temple       Berks       19560: Berks
19562            Topton       Berks       19562: Berks
19564       Virginville       Berks       19564: Berks
19565      Wernersville       Berks       19565: Berks
19567        Womelsdorf       Berks       19567: Berks
19601           Reading       Berks       19601: Berks
19602           Reading       Berks       19602: Berks
19603           Reading       Berks       19603: Berks
19604           Reading       Berks       19604: Berks
19605           Reading       Berks       19605: Berks
19606           Reading       Berks       19606: Berks
19607           Reading       Berks       19607: Berks
19608           Reading       Berks       19608: Berks
19609           Reading       Berks       19609: Berks
19610           Reading       Berks       19610: Berks
19611           Reading       Berks       19611: Berks
19612           Reading       Berks       19612: Berks
19640           Reading       Berks       19640: Berks

[2205 rows x 3 columns]

In [12]:
# drop a column
zip_codes = zip_codes.drop('ZIP/City', axis=1)
zip_codes

                   City      County
ZIP
15001         Aliquippa      Beaver
15003          Ambridge      Beaver
15004         Atlasburg  Washington
15005             Baden      Beaver
15006         Bairdford   Allegheny
15007        Bakerstown   Allegheny
15009            Beaver      Beaver
15010      Beaver Falls      Beaver
15012      Belle Vernon     Fayette
15014      Brackenridge   Allegheny
15015     Bradfordwoods   Allegheny
15017       Bridgeville   Allegheny
15018       Buena Vista   Allegheny
15019            Bulger  Washington
15020            Bunola   Allegheny
15021      Burgettstown  Washington
15022         Charleroi  Washington
15024          Cheswick   Allegheny
15025          Clairton   Allegheny
15026           Clinton      Beaver
15027            Conway      Beaver
15028          Coulters   Allegheny
15030         Creighton   Allegheny
15031             Cuddy   Allegheny
15032       Curtisville   Allegheny
15033            Donora  Washington
15034        Dravosburg   Allegheny
15035  East Mc Keesport   Allegheny
15037         Elizabeth   Allegheny
15038            Elrama  Washington
...                 ...         ...
19542  Monocacy Station       Berks
19543        Morgantown       Berks
19544       Mount Aetna       Berks
19545   New Berlinville       Berks
19547              Oley       Berks
19548        Pine Forge       Berks
19549      Port Clinton  Schuylkill
19550       Rehrersburg       Berks
19551         Robesonia       Berks
19554     Shartlesville       Berks
19555   Shoemakersville       Berks
19559       Strausstown       Berks
19560            Temple       Berks
19562            Topton       Berks
19564       Virginville       Berks
19565      Wernersville       Berks
19567        Womelsdorf       Berks
19601           Reading       Berks
19602           Reading       Berks
19603           Reading       Berks
19604           Reading       Berks
19605           Reading       Berks
19606           Reading       Berks
19607           Reading       Berks
19608           Reading       Berks
19609           Reading       Berks
19610           Reading       Berks
19611           Reading       Berks
19612           Reading       Berks
19640           Reading       Berks

[2205 rows x 2 columns]

In [13]:
# return a new dataframe of zip codes in allegheny county
allegheny = zip_codes[zip_codes['County'] == 'Allegheny']
allegheny

                   City     County
ZIP
15006         Bairdford  Allegheny
15007        Bakerstown  Allegheny
15014      Brackenridge  Allegheny
15015     Bradfordwoods  Allegheny
15017       Bridgeville  Allegheny
15018       Buena Vista  Allegheny
15020            Bunola  Allegheny
15024          Cheswick  Allegheny
15025          Clairton  Allegheny
15028          Coulters  Allegheny
15030         Creighton  Allegheny
15031             Cuddy  Allegheny
15032       Curtisville  Allegheny
15034        Dravosburg  Allegheny
15035  East Mc Keesport  Allegheny
15037         Elizabeth  Allegheny
15044          Gibsonia  Allegheny
15045         Glassport  Allegheny
15046          Crescent  Allegheny
15047          Greenock  Allegheny
15049           Harwick  Allegheny
15051         Indianola  Allegheny
15056         Leetsdale  Allegheny
15064            Morgan  Allegheny
15065   Natrona Heights  Allegheny
15071           Oakdale  Allegheny
15075       Rural Ridge  Allegheny
15076        Russellton  Allegheny
15082          Sturgeon  Allegheny
15084          Tarentum  Allegheny
...                 ...        ...
15253        Pittsburgh  Allegheny
15254        Pittsburgh  Allegheny
15255        Pittsburgh  Allegheny
15257        Pittsburgh  Allegheny
15258        Pittsburgh  Allegheny
15259        Pittsburgh  Allegheny
15260        Pittsburgh  Allegheny
15261        Pittsburgh  Allegheny
15262        Pittsburgh  Allegheny
15263        Pittsburgh  Allegheny
15264        Pittsburgh  Allegheny
15265        Pittsburgh  Allegheny
15267        Pittsburgh  Allegheny
15268        Pittsburgh  Allegheny
15270        Pittsburgh  Allegheny
15272        Pittsburgh  Allegheny
15274        Pittsburgh  Allegheny
15275        Pittsburgh  Allegheny
15276        Pittsburgh  Allegheny
15277        Pittsburgh  Allegheny
15278        Pittsburgh  Allegheny
15279        Pittsburgh  Allegheny
15281        Pittsburgh  Allegheny
15282        Pittsburgh  Allegheny
15283        Pittsburgh  Allegheny
15285        Pittsburgh  Allegheny
15286        Pittsburgh  Allegheny
15289        Pittsburgh  Allegheny
15290        Pittsburgh  Allegheny
15295        Pittsburgh  Allegheny

[143 rows x 2 columns]

In [14]:
pittsburgh = zip_codes[zip_codes['City'] == 'Pittsburgh']
len(pittsburgh)

77

In [15]:
pittsburgh[:10]

             City     County
ZIP
15201  Pittsburgh  Allegheny
15202  Pittsburgh  Allegheny
15203  Pittsburgh  Allegheny
15204  Pittsburgh  Allegheny
15205  Pittsburgh  Allegheny
15206  Pittsburgh  Allegheny
15207  Pittsburgh  Allegheny
15208  Pittsburgh  Allegheny
15209  Pittsburgh  Allegheny
15210  Pittsburgh  Allegheny