Class Activity 3
Alan Juffs
Workbook for Bill Board Top 1000

In [5]:
import pandas as pd
songs = pd.read_csv('/Users/Juffs/Documents/billboard_lyrics_1964-2015.csv', encoding ='cp1252')

You may have to find the encoding of the files.

In [10]:
songs.tail(5)

,Rank,Song,Artist,Year,Lyrics,Source
5095,96,el perdon,nicky jam and enrique iglesias,2015,enrique iglesias dime si es verdad me dijeron ...,3.0
5096,97,she knows,neyo featuring juicy j,2015,NaN,NaN
5097,98,night changes,one direction,2015,going out tonight changes into something red ...,1.0
5098,99,back to back,drake,2015,oh man oh man oh man not againyeah i learned ...,1.0
5099,100,how deep is your love,calvin harris and disciples,2015,i want you to breathe me in let me be your ai...,1.0

songs.head() and songs.tail() will flash first and last 5 songs.

songs.info - rank 5100 entries all present and also integers
Song non null object .. it's string. 
Lyrics - not all songs have lyrics
Source - three databases on the internet.

songs.describe() provides some statistical information. Pandas saw colums as numbers.

In [12]:
songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 6 columns):
Rank      5100 non-null int64
Song      5100 non-null object
Artist    5100 non-null object
Year      5100 non-null int64
Lyrics    4913 non-null object
Source    4913 non-null float64
dtypes: float64(1), int64(2), object(3)
memory usage: 239.1+ KB

songs.head(20)

In [13]:
songs.head(20)

,Rank,Song,Artist,Year,Lyrics,Source
0,1,wooly bully,sam the sham and the pharaohs,1965,sam the sham miscellaneous wooly bully wooly b...,3.0
1,2,i cant help myself sugar pie honey bunch,four tops,1965,sugar pie honey bunch you know that i love yo...,1.0
2,3,i cant get no satisfaction,the rolling stones,1965,,1.0
3,4,you were on my mind,we five,1965,when i woke up this morning you were on my mi...,1.0
4,5,youve lost that lovin feelin,the righteous brothers,1965,you never close your eyes anymore when i kiss...,1.0
5,6,downtown,petula clark,1965,when youre alone and life is making you lonel...,1.0
6,7,help,the beatles,1965,help i need somebody help not just anybody hel...,3.0
7,8,cant you hear my heart beat,hermans hermits,1965,carterlewis every time i see you lookin my way...,5.0
8,9,crying in the chapel,elvis presley,1965,you saw me crying in the chapel the tears i s...,1.0
9,10,my girl,the temptations,1965,ive got sunshine on a cloudy day when its cold...,3.0
10,11,help me rhonda,the beach boys,1965,well since she put me down i ve been out doin ...,3.0
11,12,king of the road,roger miller,1965,trailer for sale or rent rooms to let fifty c...,1.0
12,13,the birds and the bees,jewel akens,1965,let me tell ya bout the birds and the bees and...,3.0
13,14,hold me thrill me kiss me,mel carter,1965,hold me hold me never let me go until youve t...,1.0
14,15,shotgun,junior walker the all stars,1965,i said Ì¢shotgun shoot em for he runs now do t...,3.0
15,16,i got you babe,sonny cher,1965,they say were young and we dont know we wont f...,3.0
16,17,this diamond ring,gary lewis the playboys,1965,who wants to buy this diamond ring she took it...,3.0
17,18,the in crowd,ramsey lewis trio,1965,instrumental,3.0
18,19,mrs brown youve got a lovely daughter,hermans hermits,1965,mrs brown youve got a lovely daughter girls a...,1.0
19,20,stop in the name of love,the supremes,1965,stop in the name of love before you break my ...,1.0

Reorder the columns and delete the source column. [[ ]] is important for a dataframe.

In [14]:
songs= songs [['Year', 'Rank', 'Artist', 'Song', 'Lyrics']].
type(songs)
songs.head()

,Year,Rank,Artist,Song,Lyrics
0,1965,1,sam the sham and the pharaohs,wooly bully,sam the sham miscellaneous wooly bully wooly b...
1,1965,2,four tops,i cant help myself sugar pie honey bunch,sugar pie honey bunch you know that i love yo...
2,1965,3,the rolling stones,i cant get no satisfaction,
3,1965,4,we five,you were on my mind,when i woke up this morning you were on my mi...
4,1965,5,the righteous brothers,youve lost that lovin feelin,you never close your eyes anymore when i kiss...